name: ck_sms_plugin
description: A cross platform plugin for displaying and scheduling local
  notifications for Flutter applications with the ability to customise for each
  platform.
version: 0.0.1+1
homepage: https://capedkoala.com

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications_platform_interface: ^2.0.0+1
  platform: ">=2.0.0 <4.0.0"
  timezone: ^0.6.1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3
  plugin_platform_interface: ^1.0.3

flutter:
  plugin:
    platforms:
      android:
        package: com.capedkoala.ck_sms_plugin
        pluginClass: CKSMSPlugin
      ios:
        pluginClass: CKSMSPlugin 
      macos:
        pluginClass: CKSMSPlugin

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
